version: '3'
services:
  flask_app:
    build: .
    command: flask run --host 0.0.0.0
    environment:
      - FLASK_APP=flask_app.py
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
