version: '3'
services:
  flask_app:
    build: .
    command: flask run --host 0.0.0.0
    environment:
      - FLASK_APP=flask_app.py
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
  jupyter:
    build: .
    command: jupyter notebook --ip=0.0.0.0 --allow-root
    environment:
      - JUPYTER_TOKEN=abc123
    volumes:
      - .:/usr/src/app
    ports:
      - 8888:8888
